name: Playwright Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  e2e_tests:
    name: 'E2E Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy env
        run: cp .env.example .env

      - uses: ./.github/actions/node-install

      - name: Start Services
        run: npm run dx:up

      - uses: ./.github/actions/playwright-install

      - name: Create the database
        run: npm run prisma:migrate-dev

      - name: Seed the database
        run: npm run prisma:seed

      - uses: ./.github/actions/cache-build

      - name: Run Playwright tests
        run: npm run ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: 'packages/app-tests/**/test-results/*'
          retention-days: 30
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
